---
stages:
  - deploy
  - notify

variables:
  CI_DEBUG_TRACE: "false"
  GIT_SUBMODULE_STRATEGY: recursive

auto deploy:
  stage: deploy
  script:
    - echo "${SSH_PRIVATE_KEY}"
    - echo "${SSH_USER}"
    - echo "${SSH_HOST}"
    - echo "${REMOTE_PATH}"
    - mkdir -p ~/.ssh
    - echo "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - chmod 700 ~/.ssh
    - ssh-keyscan -p 22 ${SSH_HOST} > ~/.ssh/known_hosts
    - echo "Генерирование страниц началось"
    - hugo
    - echo "${SSH_PRIVATE_KEY}" |  tr -d ' ' | base64 --decode > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - cp ./content/.htaccess ./public/.htaccess
    - cp ./content/robots.txt ./public/robots.txt
    - echo "Запуск rsync"
    - rsync -avz -e "ssh -i ~/.ssh/id_rsa" --progress --delete public/ ${SSH_USER}@${SSH_HOST}:${REMOTE_PATH}
    - echo "Завершён деплой"
    - sh .cicd/notify-tg.sh ✅
  only:
    - master
  tags:
    - raspberry
    - ansible
    - raspberrypi
    - shell
    - ops

notify_error:
  stage: notify
  script:
  - sh .cicd/notify-tg.sh ❌
  when: on_failure
  only:
    - master
  tags:
    - raspberry
    - ansible
    - raspberrypi
    - shell
    - ops

