image: docker:19.03.12

services:
  - docker:19.03.12-dind

variables:
  CI_DEBUG_TRACE: "false"
  GIT_SUBMODULE_STRATEGY: recursive
  SSH_PK: $SSH_PRIVATE_KEY
  DOCKER_DRIVER: overlay

# before_script:
  # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
deploy fozzy:
  stage: build
  script:
    # - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --build-arg SSH_PRIVATE_KEY="${SSH_PRIVATE_KEY}" \
    --build-arg SSH_USER="${SSH_USER}" \
    --build-arg SSH_HOST="${SSH_HOST}" \
    --build-arg REMOTE_PATH="${REMOTE_PATH}"  --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    # - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    # - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master
