baseURL: "https://jtprog.ru"
theme: "papermod"
title: "SysOps"
copyright: "Mihael (jtprogru) Savin / Commit: @@@COMMIT@@@"
languageCode: "ru-RU"
defaultContentLanguage: "ru"
enableEmoji: true
enablegitinfo: true
forcesyncstatic: true
paginate: 10
canonifyURLs: true
summaryLength: 15

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-176073511-1

minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
  tdewolff:
    css:
      decimals: -1
      keepCSS2: true
    html:
      keepConditionalComments: true
      keepDefaultAttrVals: true
      keepDocumentTags: true
      keepEndTags: true
      keepQuotes: false
      keepWhitespace: false
    js:
    json:
    svg:
      decimals: -1
    xml:
      keepWhitespace: false
pluralizeListTitles: true
params:
  env: production
  comments: false
  ShowPostNavLinks: true
  editPost:
    URL: "https://github.com/jtprogru/jtprog.ru/blob/master/content"
    Text: "Edit..." # edit text
    appendFilePath: true # to aepend file path to Edit link
  label:
      text: "SysOps"
      icon: /logo.jpg
  assets:
    favicon: /favicon.ico
    disableFingerprinting: true

  opengraph: true
  twitter_cards: true
  copyright: "Mihael (jtprogru) Savin"
  title: "SysOps"
  description: "Записная книжка админа-самоучки"
  mainSections:  ["post"]
  dateFormat: "2006-01-02 15:04"
  related: true
  relatedMax: 5

  ShowReadingTime: true
  ShowShareButtons: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: true
  homeInfoParams:
    Title: "Привет, `%username%`!"
    Content: |
      Добро пожаловать на мой бложек,
      подписывайся на [канал](https://t.me/sysopschannel) и заходи в [чат](https://t.me/sysopschat), ну или просто скажи [спасибо](https://www.patreon.com/jtprogru)

  socialIcons:
    - name: telegram
      url: 'https://t.me/sysopschannel'
    - name: twitter
      url: 'https://twitter.com/jtprogru'
    - name: youtube
      url: 'https://www.youtube.com/channel/UCuGKtGjbVk-BtpLM1I6Yzrg'
    - name: github
      url: 'https://github.com/jtprogru'
    - name: gitlab
      url: 'https://gitlab.com/jtprogru'
    - name: dev
      url: 'https://dev.to/jtprogru'
    - name: discord
      url: 'https://discord.gg/zS2gNwt2Ka'
    - name: slack
      url: 'https://sysops20.slack.com'
    - name: stackoverflow
      url: 'https://stackoverflow.com/users/6744296/jtprog'
    - name: medium
      url: 'https://jtprogru.medium.com'
    - name: linkedin
      url: 'https://www.linkedin.com/in/jtprogru'
    - name: facebook
      url: 'https://www.facebook.com/sysopschannel'
    - name: instagram
      url: 'https://instagram.com/jtprogru'
    - name: keybase
      url: 'https://keybase.io/jtprog'
    - name: rss
      url: '/index.xml'
    - name: email
      url: 'mailto:mail@jtprog.ru'
    - name: unsplash
      url: 'https://unsplash.com/@jtprog'


  analytics:
    google:
      SiteVerificationTag: "7XYgVY2xnjODEkc6HA_dLMdLSQDNEQ3v5bG40MpnB0U"
    yandex:
      SiteVerificationTag: "766a09b06b27e0f2"

  entry:
    meta: ["date", "tags", "author"]
    toc: false
    tocOpen: false

  featured:
    previewOnly: true

  outputs:
    home: [ "HTML", "RSS", "JSON" ]
    section: [ "HTML", "RSS"]

  outputFormats:
    RSS:
      mediaType: "application/rss+xml"
      baseName: "manifest"
      isPlainText: true
      notAlternative: true

  taxonomies:
    category: "categories"
    tag: "tags"

  permalinks:
    post: "/:slug/"

menu:
  main:
    - name: "Patreon"
      url: "https://www.patreon.com/jtprogru"
      weight: 2
    - name: "CV"
      url: "http://savinmi.ru/"
      weight: 5
    - name: "RSS"
      url: "/index.xml"
      weight: 4
    - name: "Телеграм"
      url: "https://t.me/sysopschannel"
      weight: 1
    - name: "Чат"
      url: "https://t.me/sysopschat"
      weight: 3

frontmatter:
  date: ["date", "publishDate", "lastmod"]
  lastmod: [":git", "lastmod", "date", "publishDate"]
  publishDate: ["publishDate", "date"]
  expiryDate: ["expiryDate"]


markup:
  asciidocExt:
    attributes: {}
    backend: html5
    extensions: []
    failureLevel: fatal
    noHeaderOrFooter: true
    preserveTOC: false
    safeMode: unsafe
    sectionNumbers: false
    trace: false
    verbose: false
    workingFolderCurrent: false
  blackFriday:
    angledQuotes: false
    extensions: null
    extensionsMask: null
    footnoteAnchorPrefix: ""
    footnoteReturnLinkContents: ""
    fractions: true
    hrefTargetBlank: false
    latexDashes: true
    nofollowLinks: false
    noreferrerLinks: false
    plainIDAnchors: true
    skipHTML: false
    smartDashes: true
    smartypants: true
    smartypantsQuotesNBSP: false
    taskLists: true
  defaultMarkdownHandler: goldmark

  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: onedark
    tabWidth: 4

caches:
  assets:
    dir: ":resourceDir/_gen"
    maxAge: -1
  getcsv:
    dir: ":cacheDir/:project"
    maxAge: -1
  getjson:
    dir: ":cacheDir/:project"
    maxAge: -1
  images:
    dir: ":resourceDir/_gen"
    maxAge: -1
  modules:
    dir: ":cacheDir/modules"
    maxAge: -1

module:
  mounts:
  - source: content
    target: content
  - source: static
    target: static
  - source: layouts
    target: layouts
  - source: data
    target: data
  - source: assets
    target: assets
  - source: i18n
    target: i18n
  - source: archetypes
    target: archetypes

