---
baseURL: "https://jtprog.ru"
theme: "bear"
title: "Мишка на сервере"
copyright: "Mihael (jtprogru) Savin / Commit: @@@COMMIT@@@"
languageCode: "ru-RU"
defaultContentLanguage: "ru"
enableEmoji: true
enablegitinfo: true
forcesyncstatic: true
paginate: 10
canonifyURLs: true
summaryLength: 15

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-NK4TC343YF

minify:
  disableXML: true
  minifyOutput: true

pluralizeListTitles: true

params:
  env: production
  comments: false
  ShowPostNavLinks: true
  description: 'Записная книга самоучки'
  author: 'jtprogru'
  editPost:
    URL: "https://github.com/jtprogru/jtprog.ru/blob/master/content"
    Text: "Edit..."
    appendFilePath: true
  label:
    text: "Мишка на сервере"
    icon: /fav-light.svg
    iconHeight: 35
    # icon_dark: /fav-light.svg
    # icon_light: /fav-dark.svg
  assets:
    favicon: /favicon.svg
    favicon16x16: /favicon-16x16.svg
    favicon32x32: /favicon-32x32.svg
    apple_touch_icon: /apple-touch-icon.svg
    safari_pinned_tab: /safari-pinned-tab.svg
    disableFingerprinting: true
  cover:
    hidden: false  # hide everywhere but not in structured data
    hiddenInList: false  # hide on list pages and home
    hiddenInSingle: false  # hide on single page
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 1
    distance: 1000
    threshold: 0.2
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  opengraph: true
  twitter_cards: true
  images: ["twitter-card.svg"]
  defaultTheme: auto
  copyright: "Mihael (jtprogru) Savin"
  mainSections: ["post"]
  dateFormat: "2006-01-02 15:04"
  related: true
  relatedMax: 5

  ShowReadingTime: true
  ShowShareButtons: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: true

  homeInfoParams:
    Title: "Привет, `%username%`!"
    Content: |+
      Меня зовут Михаил и добро пожаловать на страницы моего блога.
      Подписывайся на [telegram-канал](https://ttttt.me/jtprogru_channel) или заходи в
      [telegram-чат](https://ttttt.me/jtprogru_chat) и задавай вопросы.

  socialIcons:
    - name: telegram
      url: 'https://ttttt.me/jtprogru_chat'
    - name: twitter
      url: 'https://twitter.com/jtprogru'
    - name: vkcom
      url: "https://vk.com/jtprogru_channel"
    - name: boosty
      url: 'https://boosty.to/jtprogru'
    - name: youtube
      url: 'https://www.youtube.com/channel/UCuGKtGjbVk-BtpLM1I6Yzrg'
    - name: github
      url: 'https://github.com/jtprogru'
    - name: mastodon
      url: 'https://mas.to/@jtprogru'
    - name: buymeacoffee
      url: 'https://www.buymeacoffee.com/jtprogru'
    - name: dev
      url: 'https://dev.to/jtprogru'
    - name: discord
      url: 'https://discord.gg/zS2gNwt2Ka'
    - name: medium
      url: 'https://jtprogru.medium.com'
    - name: linkedin
      url: 'https://www.linkedin.com/in/jtprogru'
    - name: unsplash
      url: 'https://unsplash.com/@jtprogru'
    - name: keybase
      url: 'https://keybase.io/jtprog'
    - name: soundcloud
      url: 'https://soundcloud.com/jtprogru/'
    - name: cv
      url: "https://savinmi.ru"
    - name: rss
      url: '/index.xml'

  analytics:
    google:
      SiteVerificationTag: "7XYgVY2xnjODEkc6HA_dLMdLSQDNEQ3v5bG40MpnB0U"
    yandex:
      SiteVerificationTag: "766a09b06b27e0f2"

  entry:
    meta: ["date", "tags", "author"]
    toc: false

  featured:
    previewOnly: true

  outputs:
    home:
      - "HTML"
      - "RSS"
      - "JSON"
    section:
      - "HTML"
      - "RSS"

  outputFormats:
    RSS:
      mediaType: "application/rss+xml"
      baseName: "manifest"
      isPlainText: true
      notAlternative: true

  taxonomies:
    category: "categories"
    tag: "tags"

  permalinks:
    post: "/:slug/"

menu:
  main:
#   - name: "Поиск"
#     url: "/search/"
#     weight: 2
    - name: "Поддержать"
      url: "/donations/"
      weight: 1

frontmatter:
  date: ["date", "publishDate", "lastmod"]
  lastmod: [":git", "lastmod", "date", "publishDate"]
  publishDate: ["publishDate", "date"]
  expiryDate: ["expiryDate"]

markup:
  asciidocExt:
    attributes: {}
    backend: html5
    extensions: []
    failureLevel: fatal
    noHeaderOrFooter: true
    preserveTOC: false
    safeMode: unsafe
    sectionNumbers: false
    trace: false
    verbose: false
    workingFolderCurrent: false

  blackFriday:
    angledQuotes: false
    extensions: null
    extensionsMask: null
    footnoteAnchorPrefix: ""
    footnoteReturnLinkContents: ""
    fractions: true
    hrefTargetBlank: false
    latexDashes: true
    nofollowLinks: false
    noreferrerLinks: false
    plainIDAnchors: true
    skipHTML: false
    smartDashes: true
    smartypants: true
    smartypantsQuotesNBSP: false
    taskLists: true
    defaultMarkdownHandler: goldmark

  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: onedark
    tabWidth: 4

caches:
  assets:
    dir: ":resourceDir/_gen"
    maxAge: -1
  getcsv:
    dir: ":cacheDir/:project"
    maxAge: -1
  getjson:
    dir: ":cacheDir/:project"
    maxAge: -1
  images:
    dir: ":resourceDir/_gen"
    maxAge: -1
  modules:
    dir: ":cacheDir/modules"
    maxAge: -1

module:
  mounts:
    - source: content
      target: content
    - source: static
      target: static
    - source: layouts
      target: layouts
    - source: data
      target: data
    - source: assets
      target: assets
    - source: i18n
      target: i18n
    - source: archetypes
      target: archetypes

