baseURL: "https://hugo.jtprog.ru"
theme: "papermod"
title: "SysOps"
languageCode: "ru-RU"
defaultContentLanguage: "ru"
enableEmoji: true
enablegitinfo: true
forcesyncstatic: true
paginate: 10
canonifyURLs: true
summaryLength: 15

# author: # Used in authorbox
#   name: "JTProg"
#   bio: "RTFM!!!"
#   avatar: "profile.png"
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-176073511-1

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  comments: true
  # hidemeta: true
  disqusShortname: "jtprog"
  label:
      text: "SysOps"
      icon: /logo.jpg
      # iconHeight: 135
  assets:
    favicon: '/logo.jpg'
  # homeInfoParams:
    # Title: "Hi there \U0001F44B"
    # Content: Welcome to my blog
  # opengraph: true # Enable OpenGraph if true
  # twitter_cards: true # Enable Twitter Cards if true
  # copyright: "Mihael (JTProg) Savin"
  title: "SysOps"
  description: "Записная книжка админа-самоучки"
  mainSections:  ["post"]
  # columns: 1 # Set the number of cards columns. Possible values: 1, 2, 3
  # Change the format of dates
  dateFormat: "2006-01-02 15:04"
  # colorTheme: "dark-violet" # dark-green, dark-blue, dark-red, dark-violet
  # mainMenuAlignment: "right" # Align main menu (desktop version) to the right side
  # authorbox: true # Show authorbox at bottom of single pages if true
  # comments: true # Enable comments for all site pages
  # related: true # Enable Related content for single pages
  # relatedMax: 5 # Set the maximum number of elements that can be displayed in related block. Optional
  # mathjax: false # Enable MathJax for all site pages
  # mathjaxPath: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path. Optional
  # mathjaxConfig: "TeX-AMS-MML_HTMLorMML" # Specify MathJax config. Optional
  # hideNoPostsWarning: false # Don't show no posts empty state warning in main page, if true
  # twitterName: "jtprogru"
  # yaMoney: "410011675062464"
  ShowShareButtons: true
  ShowReadingTime: true
  disableSpecial1stPost: true
  homeInfoParams:
    Title: "Приветствую \U0001F44B"
    Content: Добро пожаловать на мой бложек

  socialIcons:
    - name: telegram
      url: 'https://t.me/sysopschannel'
    - name: twitter
      url: 'https://twitter.com/jtprogru'
    - name: github
      url: 'https://github.com/jtprog'
    - name: gitlab
      url: 'https://gitlab.com/jtprog'
    - name: stackoverflow
      url: 'https://stackoverflow.com/users/6744296/jtprog'
    - name: linkedin
      url: 'https://linkedin.com/mihail-jtprogru-savin'
    - name: facebook
      url: 'https://www.facebook.com/sysodminium'
    - name: instagram
      url: 'https://instagram.com/jtprog'
    - name: rss
      url: '/index.xml'
    - name: email
      url: 'mailto:mail@jtprog.ru'




  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"

  entry:
    meta: ["date", "tags", "author"] # Enable meta fields in given order
    toc: false # Enable Table of Contents
    tocOpen: false # Open Table of Contents block. Optional

  # featured:
  #   previewOnly: true # Show only preview featured image

  # breadcrumb:
  #   enable: false # Enable breadcrumb block globally
  #   homeText: "Главная" # Home node text

  # social:
  #   email: "mail@jtprog.ru"
  #   jabber: "jtprog@jabber.ru"
  #   facebook: "sysodminium"
  #   twitter: "jtprogru"
  #   telegram: "sysodminium"
  #   instagram: "jtprog"
  #   linkedin: "mihail-jtprogru-savin"
  #   github: "jtprog"
  #   gitlab: "jtprog"
  #   stackoverflow: "6744296"
  #   medium: "jtprog"

  # Share: # Entry Share block
  #   facebook: true
  #   twitter: true
  #   reddit: true
  #   linkedin: true
  #   vk: true
  #   pocket: true
  #   pinterest: true

  # Manifest:
    # name: "SysOps"
    # shortName: "Binario"
    # display: "browser"
    # startUrl: "/"
    # backgroundColor: "#102020"
    # themeColor: "#1b1b1b"
    # description: "Записная книжка админа-самоучки"
    # orientation: "portrait"
    # scope: "/"

# outputFormats:
#   MANIFEST:
#     mediaType: "application/json"
#     baseName: "manifest"
#     isPlainText: true
#     notAlternative: true
#   RSS:
#     mediaType: "application/rss+xml"
#     baseName: "manifest"
#     isPlainText: true
#     notAlternative: true

outputs:
  home: ["HTML", "RSS"] #, "MANIFEST"]


# taxonomies:
#   category: "categories"
#   tag: "tags"

permalinks:
  post: "/:slug/"

menu:
  main:
  - name: "GitHub"
    url: "/github/"
    weight: 10
  - name: "Навыки"
    url: "/skillz/"
    weight: 30
  - name: "Резюме"
    url: "/resume/"
    weight: 20

# frontmatter:
#   date: ["date", "publishDate", "lastmod"]
#   lastmod: [":git", "lastmod", "date", "publishDate"]
#   publishDate: ["publishDate", "date"]
#   expiryDate: ["expiryDate"]


# markup:
  # highlight:
  #   anchorLineNos: false
  #   codeFences: true
  #   guessSyntax: false
  #   hl_Lines: ""
  #   lineAnchors: ""
  #   lineNoStart: 1
  #   lineNos: false
  #   lineNumbersInTable: true
  #   noClasses: true
  #   style: "monokai"
  #   tabWidth: 4

  # blackFriday:
  #   angledQuotes: false
  #   footnoteAnchorPrefix: ""
  #   footnoteReturnLinkContents: ""
  #   fractions: true
  #   hrefTargetBlank: false
  #   latexDashes: true
  #   nofollowLinks: false
  #   noreferrerLinks: false
  #   plainIDAnchors: true
  #   skipHTML: false
  #   smartDashes: true
  #   smartypants: true
  #   smartypantsQuotesNBSP: false
  #   taskLists: true

  # goldmark:
  #   extensions:
  #     definitionList: true
  #     footnote: true
  #     linkify: true
  #     strikethrough: true
  #     table: true
  #     taskList: true
  #     typographer: true
  #   parser:
  #     attribute: true
  #     autoHeadingID: true
  #     autoHeadingIDType: "github"
  #   renderer:
  #     hardWraps: false
  #     unsafe: false
  #     xhtml: false

# minify:
#   disableCSS: false
#   disableHTML: false
#   disableJS: false
#   disableJSON: false
#   disableSVG: false
#   disableXML: false
#   minifyOutput: false
#   tdewolff:
#     css:
#       decimals: -1
#       keepCSS2: true
#     html:
#       keepConditionalComments: true
#       keepDefaultAttrVals: true
#       keepDocumentTags: true
#       keepEndTags: true
#       keepQuotes: false
#       keepWhitespace: false
#     js:
#     json:
#     svg:
#       decimals: -1
#     xml:
#       keepWhitespace: false

# caches:
#   assets:
#     dir: ":resourceDir/_gen"
#     maxAge: -1
#   getcsv:
#     dir: ":cacheDir/:project"
#     maxAge: -1
#   getjson:
#     dir: ":cacheDir/:project"
#     maxAge: -1
#   images:
#     dir: ":resourceDir/_gen"
#     maxAge: -1
#   modules:
#     dir: ":cacheDir/modules"
#     maxAge: -1

# deployment:
#   # By default, files are uploaded in an arbitrary order.
#   # Files that match the regular expressions in the "Order" list
#   # will be uploaded first, in the listed order.
#   order: [".jpg$", ".gif$"]


#   targets:
#     # An arbitrary name for this target.
#     name: "mydeployment"
#     # The Go Cloud Development Kit URL to deploy to. Examples:
#     # GCS; see https://gocloud.dev/howto/blob/#gcs
#     # URL: "gs://<Bucket Name>"

#     # S3; see https://gocloud.dev/howto/blob/#s3
#     # For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
#     # URL: "s3://<Bucket Name>?region=<AWS region>"

#     # Azure Blob Storage; see https://gocloud.dev/howto/blob/#azure
#     # URL: "azblob://$web"

#     # You can use a "prefix=" query parameter to target a subfolder of the bucket:
#     # URL: "gs://<Bucket Name>?prefix=a/subfolder/"

#     # If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
#     cloudFrontDistributionID: <ID>

#     # Optionally, you can include or exclude specific files.
#     # See https://godoc.org/github.com/gobwas/glob#Glob for the glob pattern syntax.
#     # If non-empty, the pattern is matched against the local path.
#     # All paths are matched against in their filepath.ToSlash form.
#     # If exclude is non-empty, and a local or remote file's path matches it, that file is not synced.
#     # If include is non-empty, and a local or remote file's path does not match it, that file is not synced.
#     # As a result, local files that don't pass the include/exclude filters are not uploaded to remote,
#     # and remote files that don't pass the include/exclude filters are not deleted.
#     # include: "**.html" # would only include files with ".html" suffix
#     # exclude: "**.{jpg, png}" # would exclude files with ".jpg" or ".png" suffix


#   # [[deployment.matchers]] configure behavior for files that match the Pattern.
#   # Samples:

#   matchers:
#     #  Cache static assets for 1 hour.
#     - pattern: "^.+\\.(js|css|svg|ttf)$"
#       cacheControl: "max-age=3600, no-transform, public"
#       gzip: true
#     - pattern: "^.+\\.(png|jpg)$"
#       cacheControl: "max-age=3600, no-transform, public"
#       gzip: false
#     - pattern: "^.+\\.(html|xml|json)$"
#       gzip: true

module:
  mounts:
  - source: content
    target: content
  - source: static
    target: static
  - source: layouts
    target: layouts
  - source: data
    target: data
  - source: assets
    target: assets
  - source: i18n
    target: i18n
  - source: archetypes
    target: archetypes
